import type { ProviderInfo } from "./types.ts";

// Researched providers without an adapter yet. Each entry summarizes docs/connectors/<id>.md; keep them in sync.
// When an adapter ships, move its entry into connectors/<id>/info.ts and register it in registry.ts.
export const PLANNED_PROVIDERS: ProviderInfo[] = [
  {
    id: "hubspot", name: "HubSpot", status: "planned", auth: "oauth2",
    accountLabel: "Аккаунт", accountHint: "Выбирается на экране согласия HubSpot",
    setupSteps: [
      "Один раз на сервис: создайте приложение на текущей платформе разработчика HubSpot только с правами чтения.",
      "Нажмите «Авторизоваться» и выберите аккаунт клиента.",
      "При необходимости отметьте воронки закупок.",
    ],
    scopes: ["crm.objects.deals.read", "crm.objects.contacts.read", "crm.objects.companies.read", "чтение звонков, встреч, задач"],
    commercialData: ["Сделки: сумма, валюта, этап, владелец"],
    workData: ["Звонки, встречи, задачи, письма, заметки", "Связи этих действий со сделками"],
    changeCapture: "Webhook-подписки приложения + сверка по hs_lastmodifieddate",
    embed: "App Cards / App Home",
    limits: "Access-токен ~30 мин; поиск — до 10 000 результатов на запрос и ~5 запросов/с.",
    docsUrl: "https://developers.hubspot.com/docs/apps/developer-platform/build-apps/authentication/oauth/oauth-quickstart-guide",
  },
  {
    id: "pipedrive", name: "Pipedrive", status: "planned", auth: "oauth2",
    accountLabel: "Компания", accountHint: "Выбирается на экране согласия Pipedrive",
    setupSteps: [
      "Один раз на сервис: создайте приложение Marketplace (для пилота можно не публиковать) с правами чтения.",
      "Нажмите «Авторизоваться» и выберите компанию клиента.",
      "Сопоставьте типы активностей (звонок, встреча, пользовательские).",
    ],
    scopes: ["deals:read", "activities:read", "contacts:read", "users:read"],
    commercialData: ["Сделки: сумма, валюта, статус", "Статус: открыта, выиграна или проиграна"],
    workData: ["Действия по типам и отметка «выполнено»"],
    changeCapture: "Webhooks v2 + курсорная сверка",
    embed: "App extensions: панели, модальные окна, действия",
    limits: "Дневной бюджет запросов компании и лимит всплесков; до 500 записей на страницу. Запросы — только на api_domain.",
    docsUrl: "https://developers.pipedrive.com/docs/api/v1/Oauth",
  },
  {
    id: "salesforce", name: "Salesforce", status: "planned", auth: "oauth2",
    accountLabel: "Домен входа", accountHint: "login.salesforce.com, test.salesforce.com или My Domain",
    setupSteps: [
      "Один раз на сервис: создайте External Client App с OAuth web-server flow и правами api, refresh_token.",
      "Выберите продуктив, sandbox или My Domain и авторизуйтесь интеграционным пользователем с правами чтения.",
      "Администратор клиента включает Change Data Capture для Opportunity, Task, Event.",
    ],
    scopes: ["api", "refresh_token"],
    commercialData: ["Возможности: сумма, валюта, этап", "Настоящая история этапов (OpportunityHistory)"],
    workData: ["Задачи (включая звонки) и встречи"],
    changeCapture: "Change Data Capture через Pub/Sub API, хранение событий 72 часа",
    embed: "Canvas или Lightning-компонент",
    limits: "Дневная квота запросов организации; большие выгрузки через Bulk API 2.0.",
    docsUrl: "https://developer.salesforce.com/docs/platform/change-data-capture/guide/cdc-subscribe.html",
  },
  {
    id: "zoho", name: "Zoho CRM", status: "planned", auth: "oauth2",
    accountLabel: "Дата-центр", accountHint: "Определяется при авторизации (zoho.com, zoho.eu, …)",
    setupSteps: [
      "Один раз на сервис: зарегистрируйте server-based клиента в Zoho API Console с правами чтения модулей.",
      "Нажмите «Авторизоваться»; дата-центр аккаунта определяется автоматически.",
      "Отметьте воронки закупок и пользовательские модули активностей.",
    ],
    scopes: ["ZohoCRM.modules.READ", "ZohoCRM.settings.READ", "ZohoCRM.users.READ", "ZohoCRM.notifications.ALL"],
    commercialData: ["Сделки: сумма, валюта, этап, владелец"],
    workData: ["Задачи, звонки, встречи"],
    changeCapture: "Notification API (каналы до 7 дней, продление) + сверка",
    embed: "Требует отдельной проверки",
    limits: "Access-токен 1 час; 200 записей на страницу, после 2000 — page_token; кредиты по редакции.",
    docsUrl: "https://www.zoho.com/crm/developer/docs/api/v8/",
  },
  {
    id: "dynamics", name: "Dynamics 365 Sales", status: "planned", auth: "oauth2",
    accountLabel: "URL окружения", accountHint: "https://org.crm4.dynamics.com",
    setupSteps: [
      "Один раз на сервис: зарегистрируйте мультитенантное приложение Microsoft Entra с правом Dataverse user_impersonation.",
      "Введите URL окружения и авторизуйтесь; администратору тенанта может потребоваться дать согласие.",
      "Администратор клиента включает отслеживание изменений для opportunity и таблиц активностей.",
    ],
    scopes: ["Dataverse user_impersonation (делегированное чтение)"],
    commercialData: ["Возможности: оценка и итог, валюта, статус"],
    workData: ["Звонки, встречи, задачи, письма"],
    changeCapture: "Change tracking (delta links) + опциональные вебхуки",
    embed: "Custom page в model-driven приложении",
    limits: "Service protection limits: 429 с Retry-After.",
    docsUrl: "https://learn.microsoft.com/en-us/power-apps/developer/data-platform/use-change-tracking-synchronize-data-external-systems",
  },
  {
    id: "retailcrm", name: "RetailCRM", status: "planned", auth: "api_key",
    accountLabel: "Адрес системы", accountHint: "company.retailcrm.ru",
    setupSteps: [
      "Клиент создаёт API-ключ с правами только на чтение: order_read, customer_read, task_read, user_read.",
      "Введите адрес системы и ключ; сервис проверит выданные права через /api/credentials.",
    ],
    scopes: ["order_read", "customer_read", "task_read", "user_read"],
    commercialData: ["Заказы — отдельно от сделок воронки"],
    workData: ["Задачи"],
    changeCapture: "History API по sinceId",
    embed: "JS-модуль",
    limits: "Около 10 запросов/с с одного IP; до 100 записей на страницу.",
    docsUrl: "https://docs.retailcrm.ru/Developers/API/APIFeatures/APIRules",
  },
];
