import type { ProviderInfo } from "./types.ts";

// Researched providers without an adapter yet. Each entry summarizes docs/connectors/<id>.md.
export const PLANNED_PROVIDERS: ProviderInfo[] = [
  { id: "kommo", name: "Kommo / amoCRM", status: "planned", auth: "oauth2",
    accountLabel: "Поддомен аккаунта", accountHint: "company.amocrm.ru",
    setupSteps: [], scopes: [], commercialData: ["Сделки", "Контакты", "Компании", "Задачи"], workData: [],
    changeCapture: "Вебхуки (зависят от тарифа) + опрос", embed: "Виджет маркетплейса", limits: "",
    docsUrl: "https://developers.kommo.com/docs/oauth-20" },
  { id: "hubspot", name: "HubSpot", status: "planned", auth: "oauth2",
    accountLabel: "Аккаунт HubSpot", accountHint: "Выбор аккаунта при авторизации",
    setupSteps: [], scopes: [], commercialData: ["Deals", "Contacts", "Companies", "Engagements"], workData: [],
    changeCapture: "Webhook-подписки приложения", embed: "App Cards / App Home", limits: "",
    docsUrl: "https://developers.hubspot.com/developer-platform-basics" },
  { id: "pipedrive", name: "Pipedrive", status: "planned", auth: "oauth2",
    accountLabel: "Компания Pipedrive", accountHint: "Выбор компании при авторизации",
    setupSteps: [], scopes: [], commercialData: ["Deals", "Persons", "Organizations", "Activities"], workData: [],
    changeCapture: "Webhooks v2", embed: "App extensions", limits: "",
    docsUrl: "https://developers.pipedrive.com/docs/api/v1/Oauth" },
  { id: "salesforce", name: "Salesforce", status: "planned", auth: "oauth2",
    accountLabel: "Домен организации", accountHint: "company.my.salesforce.com",
    setupSteps: [], scopes: [], commercialData: ["Opportunities", "Accounts", "Contacts", "Tasks", "Events"], workData: [],
    changeCapture: "Change Data Capture (Pub/Sub API)", embed: "Canvas", limits: "",
    docsUrl: "https://developer.salesforce.com/docs/platform/change-data-capture/guide/cdc-subscribe.html" },
  { id: "zoho", name: "Zoho CRM", status: "planned", auth: "oauth2",
    accountLabel: "Дата-центр", accountHint: "zoho.eu / zoho.com",
    setupSteps: [], scopes: [], commercialData: ["Deals", "Contacts", "Accounts", "Activities"], workData: [],
    changeCapture: "Notification API (продление каналов)", embed: "Требует исследования", limits: "",
    docsUrl: "https://www.zoho.com/crm/developer/docs/api/v8/" },
  { id: "dynamics", name: "Dynamics 365 Sales", status: "planned", auth: "oauth2",
    accountLabel: "URL окружения", accountHint: "org.crm4.dynamics.com",
    setupSteps: [], scopes: [], commercialData: ["Opportunities", "Accounts", "Contacts", "Activities"], workData: [],
    changeCapture: "Change tracking (delta links)", embed: "Custom page", limits: "",
    docsUrl: "https://learn.microsoft.com/en-us/power-apps/developer/data-platform/use-change-tracking-synchronize-data-external-systems" },
  { id: "retailcrm", name: "RetailCRM", status: "planned", auth: "api_key",
    accountLabel: "Адрес системы", accountHint: "company.retailcrm.ru",
    setupSteps: [], scopes: [], commercialData: ["Заказы", "Клиенты", "Задачи"], workData: [],
    changeCapture: "History API (sinceId)", embed: "JS-модуль", limits: "",
    docsUrl: "https://docs.retailcrm.ru/Developers/API/APIFeatures/APIRules" },
];
